### ISSUE TITLE
Feature request: option to sync individual files

### ISSUE THREAD

**Issue by RickR2H** [pgmjah/filesync-vsce_#1]
Hi,

Thanks for this great extension!

I have a small feature request. Can you make is possible so that individual files can be synced. In my case the source has a lot of files, but only two neet to be synced to an other folder. Hope you can help!

Regards!

**Comment by pgmjah** [comment]
I will look into it...gimme a few days.

**Comment by pgmjah** [comment]
Feature added in 1.0.23
If you have any problems let me know.

**Comment by pgmjah** [comment]
Added in 1.0.23
