### ISSUE TITLE
No inputs were found in config file '~/.vscode/extensions/pgmjah.filesync-1.0.24/tsconfig.json'

### ISSUE THREAD

**Issue by weilin15831** [pgmjah/filesync-vsce_#2]
There's an error message in vscode problem window as below:
No inputs were found in config file '~/.vscode/extensions/pgmjah.filesync-1.0.24/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["node_modules","**/*"]'.
Seems like it does not cause any issues, but how I can remove this error message as there's one error message icon in the status bar that confuses me.

**Comment by pgmjah** [comment]
Try removing the ‘*’ in the paths…you just supply a path, not a file name, or mask. 

Also, I’m not sure relative paths work…don’t recall testing that…you may have to specify the full path to the directories you want to sync/ignore/etc…but, if it works, then great.

**Comment by weilin15831** [comment]
> Try removing the ‘*’ in the paths…you just supply a path, not a file name, or mask. Also, I’m not sure relative paths work…don’t recall testing that…you may have to specify the full path to the directories you want to sync/ignore/etc…but, if it works, then great.
> […](#)

Thanks. It's gone when there's one or more 'fsconfig.json' files exist in workspace. Sorry about that, I just even hadn't tried in the workspace.
